### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by LastAvenger** [LastAvenger/srain#1]
- [x] found basic UI frame
- [x] rewrite GtkStackSidebar, gtk sucks!
- [x] callback event of UI
- [x] log module (progarm log) just a macro
- [x] exception handel of UI module?
- [x] IRC module
- [x] adaptation of UI and IRC module
- [x] beautiful theme
- [x] system trayer
- [x] **python3 plugin support**

any more?

:sob: looks so hard....

**Comment by LastAvenger** [comment]
- [ ] prefs
- [ ] more irc command
- [ ] another theme (dark)

**Comment by LastAvenger** [comment]
ok, srain just work.
